### ISSUE TITLE
graceful-shutdown with Spring Boot 2.0 (rc2)

### ISSUE THREAD

**Issue by cla-pro** [SchweizerischeBundesbahnen/springboot-graceful-shutdown#4]
it would be greate that this shutdown works with spring boot 2.0

**Comment by ngrigoriev** [comment]
I wonder what did not work for you? I have just tried it with 2.1.0 and it did seem to work.

**Comment by manuelwallrapp** [comment]
Back then it was not released for Springboot 2.0. We made a Springboot 2.0 Version which works.
