### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by vorburger** [SchweizerischeBundesbahnen/springboot-graceful-shutdown#6]
Grüezi SBB, this is semi serious :

This is a nice project (although containers of course can and should be able to just be shot even with in flight transactions any time without business impact..). But what I was really looking for :-) when Google-ing "SBB issue tracker" (and finding this), was a repo on GitHub even with no code but just Issues to propose this :

The SBB Android Tickets App could have aIl a button "buy class upgrade", sur un billet existant?

I fully expect you to just close this issue here as soon as you see it... ;) But maybe you could seriously internally propose both the enhancement idea for the Android app, as well as having a new repo, in a more appropriate internal forum?

**Comment by manuelwallrapp** [comment]
Hi Michael

I will gracefully close your issue.. ;-)
A soft shutdown of anything is always better than 'pulling the power plug'. So if we have a choice we prefer first the graceful shutdown over just kill the app. 

Thanks for your idea. I will redirect your proposal to the mobile departement. 

I don't understand your second proposal of a repo in an internal form.

Best regards

Manu

**Comment by vorburger** [comment]
@manuelwallrapp hoi, cool - danke!

**Comment by manuelwallrapp** [comment]
Hi Michael

Was nice to meet you at Voxxed days. The Mobile PO's are checking your request. 

Best regards

Manu
